### ISSUE TITLE
Serialization robustness & correctness

### ISSUE THREAD

**Issue by danwallach** [danwallach/ElectionGuard-TypeScript#11]
- Deserialization --> what if a required field is missing? (`@Transform` annotations, e.g., in chaum-pedersen code)
- Compatibility with the latest schema from Microsoft

**Comment by shreyasminocha** [comment]
In section 4.1.4, the v1.02 spec says that the `is_write_in` field is a `string`. It's supposed to be a `boolean`, though, right?

**Comment by shreyasminocha** [comment]
Do we need codecs for the classes in `submitted-ballot.ts` and `plaintext-ballot.ts`? I'm working on the `ballot-serialization` branch, by the way.

**Comment by danwallach** [comment]
Yeah, we're going to need codecs for all that stuff. I'm meanwhile working on the `main` branch and will soon be pushing a big chunk of new code to deal with encryption and decryption, plus a ton of tiny changes elsewhere. Please don't merge anything yet.
