### ISSUE TITLE
Packaging and distribution with npm

### ISSUE THREAD

**Issue by danwallach** [danwallach/ElectionGuard-TypeScript#12]
At some point, we want to distribute a package via npm. Set everything up so it's easy to do.

**Comment by DJunge-w** [comment]
Private npm repository?

**Comment by shreyasminocha** [comment]
It's been [done](https://www.npmjs.com/package/electionguard) :tada: Share your npm username to be invited as a maintainer.

**Comment by danwallach** [comment]
Nice. I should make an account there. For now, we'll just use yours.

**Comment by danwallach** [comment]
Okay, here's my NPM account:
https://www.npmjs.com/~danwallach

Please link it in so electionguard-typescript is accessible to me.

**Comment by danwallach** [comment]
Also, I see there's another bit of TypeScript for ElectionGuard here:
https://www.npmjs.com/package/@electionguard/api-client

We need to add something to our README saying what that is and why it's different from what we are.
