### ISSUE TITLE
Support Context and Constant json input

### ISSUE THREAD

**Issue by DJunge-w** [danwallach/ElectionGuard-TypeScript#15]
Our current implementation hardcoded P, Q, and public key constants.
They need to be inputs read from context.json and constant.json defined by v1.0 ElectionGuard standard. (https://www.electionguard.vote/develop/Data_Schema/)

**Comment by danwallach** [comment]
Support for 3000 and 4000-bit constants?

**Comment by danwallach** [comment]
Fixed.
